- name: Ansible Tomcat Deploy
  hosts: webserver
  tasks:
    - name: copying file with playbook
      become: true 
      copy:
        src: /var/lib/jenkins/workspace/testing/targetpetclinic.war
        dest: /opt/apache-tomcat-8.5.69/webapps
        force: no
