---
- name: Playbook to Download and Deploy Artifact in tomcat
  hosts: webserver    
  tasks:
  - name: Create a Directory /opt/Downloads
    become: yes
    file:
      path: /opt/Downloads
      state: directory
      mode: 0755

  - name: Download Artifact from Artifactory
    become: yes
    get_url:
      url: http://34.207.119.9:8081/repository/petclinic-java/org/springframework/samples/spring-framework-petclinic/5.3.8/spring-framework-petclinic-5.3.8.war
      url_password: admin123
      url_username: admin
      dest: /opt/Downloads/spring-framework-petclinic-5.3.8.war
      mode: 0755
      
  - name: Copy File to webapp folder
    become: yes
    copy:
      src: /opt/Downloads/spring-framework-petclinic-5.3.8.war
      dest: /opt/apache-tomcat-8.5.69/webapps
      remote_src: yes
      mode: 0755
